crpt/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'crpt.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^crpt/', include('crptapp.urls', namespace="crptapp")),
    # To use default authentication system view
    url(r'^accounts/login/$', 'django.contrib.auth.views.login',
        {'template_name': 'admin/login.html'},name="my_login"),
)

crptapp/urls.py
from django.conf.urls import patterns, url
import views
from django.contrib.auth import views as auth_views

urlpatterns = patterns('',
    # List of assessments for current user (city) --> assessments.html
    url(r'^$', views.assessment_index, name='index'),
    # Edit form for assessments --> assessment_detail.html
    url(r'^(?P<assessment_id>\d+)/(?P<assessment_name>[^/]+)/$', views.get_assessment_form , name='assessment_detail'),

    # List of Risk Assessment Questions --> ra_questions.html
    url(r'^risk_assessment/(?P<ra_section_id>\d+)/(?P<assessment_id>\d+)/$', views.get_ra_section_questions , name='ra_section_questions'),
    # Statements of a Risk Assessment Question (question detail) --> question_detail.html
    url(r'^risk_assessment/(?P<ra_question_id>\d+)/(?P<ra_section_id>\d+)/(?P<assessment_id>\d+)/$', views.get_ra_question_statements , name='ra_section_question_statements'),
    # Formset of causality matrix --> ra_causality_question_detail.html
    url(r'^risk_assessment/causality/(?P<assessment_id>\d+)/(?P<ra_question_id>\d+)/$', views.get_causality_matrix_questions , name='ra_causality_matrix_questions'),

    # List of Capacity Assessment Questions --> ca_questions.html
    url(r'^capacity_assessment/(?P<ca_section_id>\d+)/(?P<ca_subsection_id>\d+)/(?P<assessment_id>\d+)/$', views.get_ca_subsection_questions , name='ca_subsection_questions'),
    # Capacity Assessment GenericStatement detail form -->
    url(r'^(?P<statement_id>\d+)/$', views.get_ca_generic_statement_form , name='ca_generic_statement_detail'),
    # Capacity Assessment Question Statements by assessment and hazard -->
    url(r'^capacity_assessment/capacity_questions/(?P<assessment_id>\d+)/(?P<hazard_id>\d+)/(?P<ca_subsection_id>\d+)/$', views.get_ca_subsection_questions_by_hazard, name='ca_statement_detail_by_hazard'),
    # Capacity Assessment Question Statements by assessment and question
    url(r'^capacity_assessment/(?P<assessment_id>\d+)/(?P<question_id>\d+)/$', views.get_ca_statement_by_assessment_question, name='ca_statement_detail_by_question'),
    # Assessment  Statement detail
    url(r'^capacity_assessment/hazard_question/(?P<assessment_id>\d+)/(?P<hazard_id>\d+)/(?P<statement_id>\d+)/$', views.get_ca_statement, name='ca_statement_detail_by_id'),


    # Necessary to get widgets from admin running OK
    (r'^admin/jsi18n/', 'django.views.i18n.javascript_catalog'),

)

crptapp/forms.py
from django.forms import ModelForm
from models import Assessment,SpatialUnitType
import django.db
from django.db import models


class AssessmentForm(ModelForm):
    """

    """

    class Meta:
        model = Assessment
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)
        sut = django.db.models.ForeignKey(SpatialUnitType)
        self.fields['new_field']=sut

crptapp/views.py
# -*- coding: utf-8 -*-

from django.http import HttpResponse
from django.template import RequestContext, loader
from models import Assessment, RiskAssessmentSection, \
    CapacityAssessmentSection, AssessmentRAQuestionStatement, \
    Actor, RiskAssessmentQuestion, Hazard, \
    RiskAssessmentQuestionset, AssessmentHazardCausality, \
    CapacityAssessmentQuestionSet, CapacityAssessmentQuestion, \
    AssessmentCAQuestionStatement, CapacityAssessmentSubsection, \
    MeetingAttendanceValues, MeetingFrequencyValues, \
    EffectivenessValues, YesNoValues
from django.shortcuts import render_to_response
from django.forms.models import modelformset_factory
from django import forms
from django.views.decorators.csrf import ensure_csrf_cookie
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
import logging

from crptapp.settings import *

logger = logging.getLogger(__name__)

@ensure_csrf_cookie
@login_required
def get_assessment_form(request, assessment_id=None, assessment_name=None):
    """
    View for creating/editing an assessment

    :param request:
    :param assessment_id:
    :param assessment_name:
    :return:
    """
    AssessmentFormSet = modelformset_factory(Assessment,max_num=1,
         widgets={'initial_date': \
                      forms.TextInput(attrs={'class':'vDateField'}),
                  'final_date': forms.TextInput(attrs={'class':'vDateField'}),
                  'last_update': forms.HiddenInput()
                  })
    num_errors = 0
    if request.method == 'POST':
        formset = AssessmentFormSet(request.POST, request.FILES)
        if formset.is_valid():
            formset.save()
            return render_to_response("crptapp/assessments.html",
                                {'assessment_list':Assessment.objects.all()})
        else:
            if format(len(formset.errors) > 0):
                num_errors = len(formset.errors[0])
    else:
        query_set = Assessment.objects.filter(pk=assessment_id)
        formset = AssessmentFormSet(queryset = query_set)
    return render_to_response("crptapp/assessment_detail.html", {
        "formset": formset,
        "num_errors":num_errors,
        "assessment_name":assessment_name},
        context_instance=RequestContext(request))

@login_required
def assessment_index(request):
    """
    View for the assessment list
    TODO: filter by user/city

    :param request:
    :return:
    """

    assessments = Assessment.objects.all()
    ra_sections = RiskAssessmentSection.objects.all()
    ca_sections = CapacityAssessmentSection.objects.all()
    template = loader.get_template('crptapp/assessments.html')
    context = RequestContext(request, {
        'assessments': assessments,
        'ra_sections': ra_sections,
        'ca_sections': ca_sections,
    })
    return HttpResponse(template.render(context))

@login_required
def get_ca_subsection_questions(request, ca_section_id, ca_subsection_id,
                                assessment_id):
    """
    View for the ca subsection questions
    :param request:
    :param ra_section_id:
    :param assessment_id:
    :return:
    """

    # only questions not hazard-related

    assessment = Assessment.objects.get(pk=assessment_id)

    ca_section = CapacityAssessmentSection.objects.get(pk=ca_section_id)
    ca_subsection = CapacityAssessmentSubsection.objects.get(pk=ca_subsection_id)
    ca_question_list = []
    num_hazard_related_questions = 0
    ca_questionset_list = \
        CapacityAssessmentQuestionSet.objects.filter(ca_subsection_id=
                                                     ca_subsection_id).\
            order_by('ca_subsection','code')
    print("Questionsetlist Len: " + format(len(ca_questionset_list)))
    for ca_questionset in ca_questionset_list:
        # exclusion in filter is_by_hazard
        ca_question_list.extend(
            CapacityAssessmentQuestion.objects.filter(ca_questionset=
                                                      ca_questionset,
                                                      is_by_hazard=False).
            order_by('ca_questionset','code'))
        # check if any question hazard-related
        num_hazard_related_questions += \
            CapacityAssessmentQuestion.objects.filter(ca_questionset=
                                                      ca_questionset,
                                                      is_by_hazard=True).\
                count()

    paginator = Paginator(ca_question_list, 25) # Show 25 items per page
    page = request.GET.get('page')
    try:
        questions = paginator.page(page)
    except:
        questions = paginator.page(1)
    return render_to_response('crptapp/ca_questions.html',
        {"questions": questions,\
        "assessment":assessment, \
        "num_hazard_related_questions":num_hazard_related_questions,\
        "ca_subsection":ca_subsection,\
        "ca_section":ca_section})

@login_required
def get_ca_subsection_questions_by_hazard(request, assessment_id,
                                          ca_subsection_id, hazard_id):
    """
    View for ca subsection questions block by hazard
    :param request:
    :param assessment_id:
    :param ca_subsection_id:
    :param hazard_id:
    :return:
    """
    assessment = Assessment.objects.get(pk=assessment_id)
    ca_subsection = CapacityAssessmentSubsection.objects.get(pk=
                                                             ca_subsection_id)
    ca_section = ca_subsection.ca_section
    hazard = Hazard.objects.get(pk=hazard_id)
    # selection of question statements, no questions, to show each description
    ca_question_list = AssessmentCAQuestionStatement.objects.filter(
        assessment=assessment_id,
        ca_subsection=ca_subsection_id,
        hazard=hazard_id).order_by('ca_subsection', 'ca_question', 'id')

    paginator = Paginator(ca_question_list, 25) # Show 25 items per page
    page = request.GET.get('page')
    try:
        questions = paginator.page(page)
    except:
        questions = paginator.page(1)
    return render_to_response('crptapp/ca_questions_by_hazard.html', {
        "questions": questions,
        "assessment":assessment,
        "ca_section":ca_section,
        "ca_subsection":ca_subsection,
        "hazard":hazard})

@login_required
def get_ra_section_questions(request, ra_section_id, assessment_id):
    """
    View for ra section questions
    :param request:
    :param ra_section_id:
    :param assessment_id:
    :return:
    """
    assessment = Assessment.objects.get(pk=assessment_id)
    ra_section = RiskAssessmentSection.objects.get(pk=ra_section_id)
    ra_questionset_list = \
        RiskAssessmentQuestionset.objects.filter(ra_section=ra_section_id)
    question_list = \
        RiskAssessmentQuestion.objects.filter(ra_questionset=
                                              ra_questionset_list).\
            order_by('id')
    paginator = Paginator(question_list, 25) # Show 25 items per page
    page = request.GET.get('page')
    try:
        questions = paginator.page(page)
    except:
        questions = paginator.page(1)
    return render_to_response('crptapp/ra_questions.html',
                              {"questions": questions,
                               "assessment":assessment,
                               "ra_section":ra_section,})

@ensure_csrf_cookie
@login_required
def get_ca_generic_statement_form(request, statement_id):
    """
    View for generic statement form
    :param request:
    :param statement_id:
    :return:
    """
    CAGenericStatmentFormSet = \
        modelformset_factory(AssessmentCAQuestionStatement,max_num=1)

    if request.method == 'POST':
        formset = CAGenericStatmentFormSet(request.POST, request.FILES)
        if formset.is_valid():
            formset.save()
            return render_to_response("crptapp/assessments.html",
                                      {'assessment_list':
                                           Assessment.objects.all()})
        else:
            if format(len(formset.errors) > 0):
                num_errors = len(formset.errors[0])
            formset.forms[0].fields['value'] = \
                forms.ModelChoiceField(queryset=Actor.objects.all())
    else:
        query_set = \
            AssessmentCAQuestionStatement.objects.filter(pk=statement_id)
        formset = CAGenericStatmentFormSet(queryset = query_set)
        formset.forms[0].fields['value'] = \
            forms.ModelChoiceField(queryset=Actor.objects.all())

    return render_to_response("crptapp/question_detail.html", {
    "formset": formset,
    }, context_instance=RequestContext(request))

@login_required
def get_ra_question_statements(request, ra_question_id, ra_section_id,
                               assessment_id):
    """
    View for ra question statements
    :param request:
    :param ra_question_id:
    :param ra_section_id:
    :param assessment_id:
    :return:
    """
    assessment = Assessment.objects.get(pk=assessment_id)
    ra_section = RiskAssessmentSection.objects.get(pk=ra_section_id)
    RAQuestionStatmentFormSet = \
        modelformset_factory(AssessmentRAQuestionStatement,
                             max_num=len(assessment.hazards.all()))

    question_statement = \
        AssessmentRAQuestionStatement.objects.get(pk = ra_question_id)
    files_to_show = \
        ('short_term_value','mid_term_value','long_term_value','mov')

    if request.method == 'POST':
        formset = RAQuestionStatmentFormSet(request.POST, request.FILES)
        if formset.is_valid():
            formset.save()
            ra_questionset_list = \
                RiskAssessmentQuestionset.objects.filter(ra_section =
                                                         ra_section_id)
            question_list = \
                RiskAssessmentQuestion.objects.filter(ra_questionset =

crptapp/templates/crptapp/base_site.html
{% extends "crptapp/base.html" %}
{% load i18n %}

{% block title %}{{ title }} | {% trans 'City Resilience Profiling Tool' %}{% endblock %}

{% block branding %}
<h1 id="site-name">{% trans 'City Resilience Profiling Tool' %}</h1>
{% endblock %}

{% block nav-global %}{% endblock %}

crptapp/templates/crptapp/ca_questions.html
{% extends "crptapp/base_site.html" %}
{% load i18n admin_static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "crptapp/css/dashboard.css" %}" />{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}dashboard{% endblock %}

{% if not is_popup %}
{% block breadcrumbs %}

<div class="breadcrumbs">
<a href="{% url 'crptapp:index' %}">{% trans 'Assessments' %} </a> &rsaquo;
<a href="{% url 'crptapp:index' %}">{{ assessment.name }} </a> &rsaquo;
<a href="{% url 'crptapp:ca_subsection_questions' ca_section_id=ca_section.id ca_subsection_id=ca_subsection.id assessment_id=assessment.id  %}">{{ca_section.name}}</a> &rsaquo;
<a href="{% url 'crptapp:ca_subsection_questions' ca_section_id=ca_section.id ca_subsection_id=ca_subsection.id assessment_id=assessment.id  %}">{{ca_subsection.name}}</a> &rsaquo;
</div>
{% endblock %}
{% endif %}

{% block content %}
<div id="content-main">

{% if questions or num_hazard_related_questions > 0 %}
    <div class="module">
        <table>
        <caption>
            <div class="section" style="float:left;">Capacity Assessment - {{ ca_subsection.name }} questions</div>
            <div style="float:right;padding-right:18px;"></div>
        </caption>


        {% if num_hazard_related_questions > 0 %}
            <tr class="assessment-{{ assessment.object_name|lower }}">
                <th scope="row"><span class="required">Hazard-related questions: </span></th>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            {% for hazard in assessment.hazards.all %}
                <tr class="assessment-{{ assessment.object_name|lower }}">
                    <th scope="row">&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'crptapp:ca_statement_detail_by_hazard' assessment_id=assessment.id hazard_id=hazard.id ca_subsection_id=ca_subsection.id %}">{{ hazard.name }}</a></th>
                    <td>&nbsp;</td>
                    <td><a href="" class="changelink">{% trans 'Edit' %}</a></td>
                    <td>&nbsp;</td>

                </tr>
            {% endfor %}
        {% endif %}

        {% if questions%}
            <tr class="assessment-{{ assessment.object_name|lower }}">
                <th scope="row"><span class="required">Non hazard-related questions:</span></th>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            {% for question in questions %}
                <tr class="assessment-{{ assessment.object_name|lower }}">

                    <th scope="row">&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'crptapp:ca_statement_detail_by_question' assessment_id=assessment.id question_id=question.id %}">{{ question.code }}-{{ question.description }}</a></th>
                    <td>&nbsp;</td>
                    <td><a href="" class="changelink">{% trans 'Edit' %}</a></td>
                    <td>&nbsp;</td>

                </tr>
            {% endfor %}
        {% endif %}
        </table>
        </div>
<!-- <div class="submit-row" style="text-align:right;"> -->
<p class="paginator">

        {% if questions.has_previous %}
        <span class="">
            <a href="?page={{ questions.previous_page_number }}"> Previous </a>
        </span>
        {% endif %}

        <span class="this-page">
            Page {{ questions.number }} of {{ questions.paginator.num_pages }}.
        </span>

        {% if questions.has_next %}
        <span class="">
            <a href="?page={{ questions.next_page_number }}"> Next </a>
        </span>
        {% endif %}
    </span>
</p>
<!-- </div> -->

{% else %}
    <p>{% trans "You have no questions created." %}</p>
{% endif %}
</div>
{% endblock %}

{% block sidebar %}

{% endblock %}

crptapp/templates/crptapp/index.html
{% extends "crptapp/base_site.html" %}
{% load i18n admin_static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "crptapp/css/dashboard.css" %}" />{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
<div id="content-main">




         <caption>
            <div class="section" style="float:left;">TEST CAGenericStatement:</div>
            <div style="float:right;padding-right:18px;"><a href="{% url 'crptapp:ca_generic_statement_detail' statement_id=1 %}" class="addlinktoplist" style="color:white;">{% trans 'GO' %}</a></div>
        </caption>
        <br>

{% if assessments %}
    <div class="module">
        <table>
        <caption>
            <div class="section" style="float:left;">Assessments for user:  {{ user }}</div>
            <div style="float:right;padding-right:18px;"><a href="{% url 'crptapp:assessment_detail' assessment_id=0 assessment_name='New Assessment' %}" class="addlinktoplist" style="color:white;">{% trans 'Add' %}</a></div>
        </caption>


        {% for assessment in assessments %}
            <tr class="assessment-{{ assessment.object_name|lower }}">
               <!-- <th scope="row"><a href="{% url 'crptapp:assessment_detail' assessment_id=assessment.id assessment_name=assessment.name %}">{{ assessment.name }}</a></th> -->
               <th scope="row"><a href="" onClick="toggleClassElements('{{ assessment.name }}');return false;">{{ assessment.name }}</a></th>

                <td>&nbsp;</td>
                <td><a href="{% url 'crptapp:assessment_detail' assessment_id=assessment.id assessment_name=assessment.name %}" class="changelink">{% trans 'Edit' %}</a></td>
                <td>&nbsp;</td>
            </tr>
            {% for ra_section in ra_sections %}
                <!-- <tr  style="display:none"> -->
                <tr class="{{ assessment.name }}" style="display:none;">
                <th scope="row" class="ra_section">&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'crptapp:ra_section_questions' ra_section_id=ra_section.id assessment_id=assessment.id  %}">{{ ra_section.name }}</a></th>
                <td>&nbsp;</td>
                <td><a href="{% url 'crptapp:ra_section_questions' ra_section_id=ra_section.id assessment_id=assessment.id  %}" class="changelink">{% trans 'Edit' %}</a></td>
                <td>&nbsp;</td>
                </tr>
            {% endfor %}
            {% for ca_section in ca_sections %}
                <!-- <tr  style="display:none"> -->
                <tr class="{{ assessment.name }}" style="display:none;">
                <th scope="row" class="ca_section">&nbsp;&nbsp;&nbsp;&nbsp;<a href="" onclick="toggleClassElements('{{ assessment.name }}-{{ ca_section.name }}');return false;">{{ ca_section.name }}</a></th>
                <td>&nbsp;</td>
                <td>&nbsp;</a></td>
                <td>&nbsp;</td>
                </tr>
                    {% for ca_subsection in ca_section.capacityassessmentsubsection_set.all %}
                    <tr class="{{ assessment.name }} {{ assessment.name }}-{{ ca_section.name }}" style="display:none;" >
                    <th scope="row" class="ca_subsection">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <a href="{% url 'crptapp:ca_subsection_questions' ca_section_id=ca_section.id ca_subsection_id=ca_subsection.id assessment_id=assessment.id  %}">{{ ca_subsection.name }}</a></th>
                    <td>&nbsp;</td>
                    <td><a href="{% url 'crptapp:ca_subsection_questions' ca_section_id=ca_section.id ca_subsection_id=ca_subsection.id assessment_id=assessment.id  %}" class="changelink">{% trans 'Edit' %}</a></td>
                    <td>&nbsp;</td>
                    </tr>
                    {% endfor %}

            {% endfor %}

        {% endfor %}
        </table>
        </div>


    {% comment %}
    {% for app in app_list %}
        <div class="app-{{ app.app_label }} module">
        <table>
        <caption>
            <a href="{{ app.app_url }}" class="section" title="{% blocktrans with name=app.name %}Assessments in the {{ name }} application{% endblocktrans %}">
                {% blocktrans with name=app.name %}{{ name }}{% endblocktrans %}
            </a>
        </caption>




        {% comment %}
        {% for model in app.models %}
            <tr class="model-{{ model.object_name|lower }}">
            {% if model.admin_url %}
                <th scope="row"><a href="{{ model.admin_url }}">{{ model.name }}</a></th>
            {% else %}
                <th scope="row">{{ model.name }}</th>
            {% endif %}

            {% if model.add_url %}
                <td><a href="{{ model.add_url }}" class="addlink">{% trans 'Add' %}</a></td>
            {% else %}
                <td>&nbsp;</td>
            {% endif %}

            {% if model.admin_url %}
                <td><a href="{{ model.admin_url }}" class="changelink">{% trans 'Change' %}</a></td>
            {% else %}
                <td>&nbsp;</td>
            {% endif %}
            </tr>
        {% endfor %}
        </table>
        </div>
    {% endfor %}
    {% endcomment %}
{% else %}
    <p>{% trans "You have no assessments created." %}</p>
{% endif %}
</div>
{% endblock %}

{% block sidebar %}
{% comment %}
<div id="content-related">
    <div class="module" id="recent-actions-module">
        <h2>{% trans 'Recent Actions' %}</h2>
        <h3>{% trans 'My Actions' %}</h3>
            {% load log %}
            {% get_admin_log 10 as admin_log for_user user %}
            {% if not admin_log %}
            <p>{% trans 'None available' %}</p>
            {% else %}
            <ul class="actionlist">
            {% for entry in admin_log %}
            <li class="{% if entry.is_addition %}addlink{% endif %}{% if entry.is_change %}changelink{% endif %}{% if entry.is_deletion %}deletelink{% endif %}">
                {% if entry.is_deletion or not entry.get_admin_url %}
                    {{ entry.object_repr }}
                {% else %}
                    <a href="{{ entry.get_admin_url }}">{{ entry.object_repr }}</a>
                {% endif %}
                <br/>
                {% if entry.content_type %}
                    <span class="mini quiet">{% filter capfirst %}{% trans entry.content_type.name %}{% endfilter %}</span>
                {% else %}
                    <span class="mini quiet">{% trans 'Unknown content' %}</span>
                {% endif %}
            </li>
            {% endfor %}
            </ul>
            {% endif %}
    </div>
</div>
{% endcomment %}
{% endblock %}

crptapp/templates/crptapp/ra_questions.html
{% extends "crptapp/base_site.html" %}
{% load i18n admin_static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "crptapp/css/dashboard.css" %}" />{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}dashboard{% endblock %}

{% load admin_list %}

{% if not is_popup %}
{% block breadcrumbs %}

<div class="breadcrumbs">
<a href="{% url 'crptapp:index' %}">{% trans 'Assessments' %} </a> &rsaquo;
<a href="{% url 'crptapp:index' %}">{{ assessment.name }} </a> &rsaquo;
<a href="{% url 'crptapp:ra_section_questions' ra_section_id=ra_section.id assessment_id=assessment.id  %}">{{ra_section.name}}</a>
</div>
{% endblock %}
{% endif %}

{% block content %}
<div id="content-main">

{% if questions %}
    <div class="module">
        <table>
         <caption>
            <div class="section" style="float:left;">{{assessment.name}} - {{ra_section.name}} questions </div>
            <div style="float:right;padding-right:18px;"></div>
        </caption>


        {% for question in questions %}
            <tr class="assessment-{{ assessment.object_name|lower }}">

                {% if question.code == "RA04QS032Q001"%}
                    <th scope="row"><a href="{% url 'crptapp:ra_causality_matrix_questions' assessment_id=assessment.id  ra_question_id=question.id %}">{{ question.description }}</a></th>
                    <td>&nbsp;</td>
                    <td><a href="{% url 'crptapp:ra_causality_matrix_questions' assessment_id=assessment.id  ra_question_id=question.id %}" class="changelink">{% trans 'Edit' %}</a></td>
                    <td>&nbsp;</td>
                {% else %}
                    <th scope="row"><a href="{% url 'crptapp:ra_section_question_statements' ra_question_id=question.id ra_section_id=question.ra_questionset.ra_section.id assessment_id=assessment.id  %}">{{ question.description }}</a></th>
                    <td>&nbsp;</td>
                    <td><a href="{% url 'crptapp:ra_section_question_statements' ra_question_id=question.id ra_section_id=question.ra_questionset.ra_section.id assessment_id=assessment.id  %}" class="changelink">{% trans 'Edit' %}</a></td>
                    <td>&nbsp;</td>
                {% endif%}

            </tr>

        {% endfor %}
        </table>
        </div>
<!-- <div class="submit-row" style="text-align:right;"> -->
<p class="paginator">

        {% if questions.has_previous %}
        <span class="">
            <a href="?page={{ questions.previous_page_number }}"> Previous </a>
        </span>
        {% endif %}

        <span class="this-page">
            Page {{ questions.number }} of {{ questions.paginator.num_pages }}.
        </span>

        {% if questions.has_next %}
        <span class="">
            <a href="?page={{ questions.next_page_number }}"> Next </a>
        </span>
        {% endif %}
    </span>
</p>
<!-- </div> -->

{% else %}
    <p>{% trans "You have no questions created." %}</p>
{% endif %}
</div>
{% endblock %}

{% block sidebar %}

{% endblock %}